import grpc
from app.config import settings

# Note: These files are generated by protoc compiling video_service.proto
# If they are not compiled yet, we define a fallback placeholder structure
try:
    from app.grpc_clients import video_service_pb2
    from app.grpc_clients import video_service_pb2_grpc
    PROTOC_COMPILED = True
except ImportError:
    PROTOC_COMPILED = False

class VideoEngineClient:
    def __init__(self):
        self.target = f"{settings.CPP_ENGINE_HOST}:{settings.CPP_ENGINE_PORT}"

    async def render_video(
        self,
        task_id: str,
        script_id: str,
        video_url: str,
        audio_url: str,
        resolution: str = "1080p",
        delta_caching: bool = True,
        auto_ducking: bool = True
    ):
        if not PROTOC_COMPILED:
            raise RuntimeError(
                "gRPC protobuf stubs are not compiled yet. "
                "Please run: python -m grpc_tools.protoc -I=backend/cpp_engine/proto "
                "--python_out=backend/src/grpc_clients --grpc_python_out=backend/src/grpc_clients "
                "backend/cpp_engine/proto/video_service.proto"
            )

        async with grpc.aio.insecure_channel(self.target) as channel:
            stub = video_service_pb2_grpc.VideoEngineStub(channel)
            request = video_service_pb2.RenderRequest(
                task_id=task_id,
                script_id=script_id,
                video_url=video_url,
                audio_url=audio_url,
                resolution=resolution,
                delta_caching=delta_caching,
                auto_ducking=auto_ducking
            )
            try:
                response = await stub.Render(request)
                return response
            except grpc.RpcError as e:
                # Handle gRPC error
                raise RuntimeError(f"gRPC call failed: {e.details()} (code: {e.code()})")
