# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'video_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x05video\"\x9a\x01\n\rRenderRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\tscript_id\x18\x02 \x01(\t\x12\x11\n\tvideo_url\x18\x03 \x01(\t\x12\x11\n\taudio_url\x18\x04 \x01(\t\x12\x12\n\nresolution\x18\x05 \x01(\t\x12\x15\n\rdelta_caching\x18\x06 \x01(\x08\x12\x14\n\x0c\x61uto_ducking\x18\x07 \x01(\x08\"y\n\x0eRenderResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\noutput_url\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x03\x12\x15\n\rerror_message\x18\x05 \x01(\t2D\n\x0bVideoEngine\x12\x35\n\x06Render\x12\x14.video.RenderRequest\x1a\x15.video.RenderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENDERREQUEST']._serialized_start=31
  _globals['_RENDERREQUEST']._serialized_end=185
  _globals['_RENDERRESPONSE']._serialized_start=187
  _globals['_RENDERRESPONSE']._serialized_end=308
  _globals['_VIDEOENGINE']._serialized_start=310
  _globals['_VIDEOENGINE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
